---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre-web
      version: 20.5.24
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    persistence:
      data:
        readOnly: true
        mountPath: /books
        enabled: true
        type: nfs 
        path: /mnt/AI_Storage/Calibre_library
        server: "10.0.50.10"
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
    ingress:
      main:
        ingressClassName: internal
        enabled: true
        hosts:
          - host: calibre-web.cloud.dev.local
            paths:
              - path: /
        tls:
          - hosts:
              - calibre-web.cloud.dev.local
   
