apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:guvL+k7vA2s6bugfOHheT3s0iVaUYBi//vfjAkfN9XnRuQAPRj/WSD1EVlly4ehvN8fv77W5mEDLgF2KY7zTbWc=,iv:o8coi+fMGZB8OUFD+dBh2xjER/HTvI/aBe7Xv0VoV+s=,tag:nZcj3WA5o/HgPf9kVMOYEQ==,type:comment]
    #ENC[AES256_GCM,data:+nne54SSSFh4vQWqyxd9IG3ljXoJx7w7ipK1mfZCkjasSOwhhCoJQRCbC5M=,iv:CiMFT3sUPDiIJNKokljO0NXYVLsYQoyjjvxEDV+88qU=,tag:SVFva9AgepVnWD7kkk6k3w==,type:comment]
    VIP: ENC[AES256_GCM,data:JiCUK04cMawm0A==,iv:VCEc36Gt5Ids+AB6gP5RJBnyswwDXshTEej9SgNF/sM=,tag:qOkFi+LGow4m8/z5L4AkNQ==,type:str]
    #ENC[AES256_GCM,data:2mOID6KXvPnHgdWJ6kdCoMIdK+FFrOnibTIa,iv:ItjnF58IVxsN8YBJf3gw1X7c3j0e45LnQIWCeNSKxDQ=,tag:aEP5Jsf1vKRTs2txAk/MhA==,type:comment]
    #ENC[AES256_GCM,data:7HAnSgJrqZrhUeaVQsUBdJH5xzyB3CrL2xyN9nJvf2zAmqx6lKW/fwyB6p/qTSi2dj66uKWke3onFt7VmBCf+XutkR7O42cMB4LvE3OwSwk0IdmLn1sEjmA=,iv:P9wnCmGA+AJwmD61Cg1mettf9mJkXWXSfW+NwJqzf44=,tag:KPOLRFe4o90vFAFdSt91pQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:QLERckoqct/3Gg==,iv:QPx9qYxbk7mDWrpMftQJaCFdhylrRrkltN48cyLxmIE=,tag:Ap+Cekuz1I+Md4ydu7nzuw==,type:str]
    #ENC[AES256_GCM,data:U5YCMO/+5N5Y6GV7eV/gX+uzZkoryqanPeRCtPlFA9yw4Q==,iv:/7XQ9z7R60Titt/gDKtWohIqFU+ebiVBxkXEc/DBbBA=,tag:oA7UCLmYGyvSRnCTFsh8zg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:j1U6yAG3zhe5,iv:GMN6fZn/AAtqU7JgHe8yNU2Rm1FXjtPfVFPN3CsChWg=,tag:B3LhX8ukbh1QoxHPu+IcvQ==,type:str]
    #ENC[AES256_GCM,data:Zf7AMnICIRx8YRzz5+taVQ6TpFL3a3ihEIACWmI1a3JBnE1qjibHBzEd09kyEEE=,iv:ooaXiIQJ//YTFyt+VHNDNXVWX6SBFTJPQD3MiahnYDE=,tag:k+y1hYSckP0d3LpV411mUw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:8DmdYFjGUOskUg8DxdtfS0K57ZoAOg==,iv:EKuPCChY5c3vkDpmwkB1SfiwJa+GyEZLEIIKZmqaQG0=,tag:+j4zK8K9TfcGLb3lQY5yZQ==,type:str]
    #ENC[AES256_GCM,data:h0O2rEaf8vl6I0iRc1llhBLPkGpT2luoNXFuMfavBYbMpUNLMoWK8tMtI+PRI63lD0Yz+kt1ONyEK1jXzMHMg7AJxxHqyN3+F9DjO0kh7j863A==,iv:WOF526PxThyOhYNDrS0TqMAt94b88a2qI8Q4mcMvXOk=,tag:biJ7d7FECqJixFXjwwjNFA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:bU97reEGVoC8ew==,iv:V3A0MB9vQ4yihBbtQie5/3AOUXaC6qoUR2ODOmoQTu4=,tag:zdLbEENFUlqfOy8hsDWeOg==,type:str]
    #ENC[AES256_GCM,data:e2k38TItOHDjdiJEDXe36v7V14V2aD0HuiLc9QWMdiJV,iv:oMiVXc+xJebOdYUUXWzdWocHc7bmyS0LZNAdvXO3vyg=,tag:ZcSSKIDXHJsCzODOH7yfrQ==,type:comment]
    BLOCKY_IP: ENC[AES256_GCM,data:xO4Z4TJmruQWPw==,iv:bNepGhhzoT1d/HDE+//fYiK/r/+MuvI+qXmn3UfGCZo=,tag:xYT7jtdo3S3exMWzir8cYw==,type:str]
    #ENC[AES256_GCM,data:0U/YmnqwvNGdK+ej+zs9fLCNg5Vt+20i5oUQs9C6dqihdWDVuCpIPr2uHWvzKBRVgduYChaiUDK2JqNqPWfxP5MalYBkMRMRbKSiAz7a9N0=,iv:H5sPKrC0m6oyQY6gpFgAOywckdXvawE3s+/AXLM+QVE=,tag:hywDuOzjlesoNWc8ky3Yjg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:NTy7batl9PbwWA==,iv:4zKtYqqSmFhuKldq7LrVZLcxZhMoh58Q5YaU96d5Kc4=,tag:tnZ75FcE2hLfZVIqRt1aug==,type:str]
    #ENC[AES256_GCM,data:K04riNCIWA2nc4rOhiOogaminrPOm3/zKg1uEOM4z5xo3CM8wlsayJoAPE91v7XOo/PHvjOvHOsXBrzwncw9wspfczy7C3+dyCcxjXiXqUUyZJtbp5RP,iv:6VmzGCxlrny4DpVqA0sedAnNmVJzPeFNAVss7dPO8Ds=,tag:s5/277sTlotHrRfJD2YtLg==,type:comment]
    #ENC[AES256_GCM,data:W8AY198NVNeAsco1RRLsetG5kMVsA9uwaZKWy0ZrMP8wpY6FK/VYKksrSR1wDWMXfzGmsE5xybXjCE9axQhhiOYNHOJ8DTtCYAY/8otN+OFmyraXfzHaS8mMG+2+GYHc0BOX6Csn5p6U2yN6EHYUIlQTN6rcpJBYyB4zRQ==,iv:/JgWTIaceA3VjAd8wf5aMhP/HitPgHyimLhuQ7zX7W8=,tag:O7ms69aZlTGiy+34dZqnXQ==,type:comment]
    #ENC[AES256_GCM,data:6GYnqOi5YOlXDZUCpQi/Oap5jfVIZSKTWKigYi+4erjGf099XSsNIFbtNnClSw5jJZnUCppkouHQfTI0YosRJ7kyJFSOPY33G0PkArluAI0=,iv:mgtVjEHMSikAicUmpdt7nASa+ndrcedlVboOSC+oPXc=,tag:F+oh+hSwq8w1dnY+pWiinw==,type:comment]
    #ENC[AES256_GCM,data:5cphEOdCU6clJKZk+PYJZSGIAwMRZHdsORj3NvyWC0+ziZTV+Jhf71q1oS05mSr5ynXYW0Vp,iv:gaq8LCLGeiLjeI/z+sl23xTDPWwiFU8yDKG7Z/HQZY0=,tag:2OW3IrRFngTg/0dtsvQKog==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:cFWIwRZ+IfdTtZI13puEndY=,iv:sjpHnhAJBMw9vx/VUe03t04k6SfpgkGfWb5PE4Vg5Uc=,tag:NazLMG/yULURu7fjVEJvxQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:96HJeME4iDw/zxYJrvPSO+xJSHj/rA==,iv:JfY/11OQ6IJ/4ypuAhVASYljwZA4PKoWBGE59fd+LPY=,tag:Ix90V8zzATv+c+jRK74EEQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Z2LA/CtzGR2zGAcC2sWbJViqzXJcMkxHe6GRY0XPXa/xOWNqbNItiQ==,iv:AMUuKkkHnaTtkda/rkLNSMZLd4qvZJRHmUPcPYp+VBQ=,tag:/X2a5Lpo0fUMpJOJzEssGg==,type:str]
    #ENC[AES256_GCM,data:qiWnor7FShJteZtYAeYlRkcPZULEySZKxf+DSym7WGd7nG/1UWXlkU+Q0aB6+v0fiuGNQ4bMauk=,iv:VoWu8VarIlTGFNE5U9fpA8/1HpIJRa/GhindpuU6+f0=,tag:RgTKb3ptfARqV9dH85rrtQ==,type:comment]
    #ENC[AES256_GCM,data:ASEp63nwqk5D1dv+4MN7NqP2OBSutQkTZw==,iv:zmLRvJ91MjgUEbE6M6wJsAMIh69pCUSQPCwb+2mtsBw=,tag:xCKgogFWcTqdBbj5ujuq7g==,type:comment]
    #ENC[AES256_GCM,data:Lz9U2NzPEGdNJZaI4kNuHAN+g4lNsWC1gM7T//Lzgyu78WhfI0NDHmgNjJL+3KpTHA9fzQ+k0Tz0fvyQhqB6+/+WoTGWzeCaDRcfjws=,iv:QjVVFvVHXmpEOm668mDNntY+iZP+P9x3boFCWTsffzo=,tag:LtWY2RwwrY/D5BRkqST3Vg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:foc0JBKOqG3PP4XhAxwLG5waFtpULpVr3VFakTlXKzaD2xNdxC++6A10rPOEaYmjtLH15GtJwDfvBcIO1vA=,iv:npp7F22P0KTNMjEgBcrIgzg1G9DDn9qFPaRuKHWkOI8=,tag:px5MWVSY47zWZ5D2I/oskw==,type:str]
    #ENC[AES256_GCM,data:i+Cm17xT/a6e62bmrBU1pOCEklhiszZ+1lW5rPRUchtGRucQlnKlYOjzbB/rmtCxc0O86KgsL/K0KKqmRdkdIzdxmGseRDk=,iv:aix5Lrtp9A19qR9aPTpVv1NFt2npsxTTkyb4Oeg4CJk=,tag:k/GpCliYhl/odcdSJ4Co7g==,type:comment]
    #ENC[AES256_GCM,data:ppTOVwuVW8ptc4lBjsXq/wVcQs+GZCoRNoV3qUew7KoEYtPDJtsYwB6pP+rvPyMQMP4HRDGQ,iv:PS8Cm1+iJRSCJqCEPzEVe/QnpBE4OBwLPnKbLRLWZe4=,tag:L0xZ6qACNI3+vr0wFtwoUA==,type:comment]
    #ENC[AES256_GCM,data:vEc2aloYNqAyw4beusoEbUf3SIh+hnjzDxItva5LHSnpuOw=,iv:VVG2G/qJuSk4VQt9c2p/8pOkGV1bWnZufGXTyzklOh4=,tag:x9kk8v8D4cf58+A1ZEvbhQ==,type:comment]
    #ENC[AES256_GCM,data:iNd1f/YzJrOOr5B2e7R7xGqw6lh6ysFk54rO6+Srkv4zZ/reegwF,iv:ouL0y9Ftob9C1drpYsk0qsSf818+5AfGJS4vJU5HplA=,tag:ZEIRuOeVIlYdSfR3oiVidQ==,type:comment]
    #ENC[AES256_GCM,data:7in6J2qY6HmuWy3l7Nw=,iv:hBWG1Vhc9W7tuN2G0dMrPxUHssq+VM6Xqz6WZ/dRhrI=,tag:rKy+Wy2N7wu96y65BuWD0g==,type:comment]
    PODNET: ENC[AES256_GCM,data:0ljrWgOjzkG+yvlI0w==,iv:Nr6SDQRkJtr/VftVu3OPTTmj6Q2b+HvpJlMRoC9BTUs=,tag:NUTKc6w+xnb6aISNUlcfEw==,type:str]
    SVCNET: ENC[AES256_GCM,data:/liDkunMN1TlBbdEOQ==,iv:IiMAVjJYq+pidkRDc3HnvZVctBZIivWrUumXKng5v9o=,tag:ko2bu1BTzKvJo5CW+bJkAQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:Nmz9EQ==,iv:fpGf6LED6Gh18rpTF9t23XAaRhPeVibZP9knjvaZCB4=,tag:bXQjgBNJKcBiBQ34uZv9hQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaDNVNjZQTDhvQ0JXV1hZ
            Yy9jTmQwcXl5UFZ4VVJNQnVqdnlrZkZyTmdRCnV2clJTd1NMRnlOQitIMFBZUzdz
            ZEJ2YTZaczZZNlBPQzVraHBaaENLeWsKLS0tIGNYZlJVRTZIK2NtSG5BYzB2REdG
            K25uaTdUdXlOVU9KQ0N5VDRRb0dIMUUKFD9t/bNQJyc/0c6v4fspbMZzRPcnkdYD
            43/edS15UBpRq+3t8GXpOTLE0qfbLjpNpG6E4ogWJPaJBLrg6olkhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T10:53:43Z"
    mac: ENC[AES256_GCM,data:LXSJ4dS9gMaV7EGLWmljFNBzHbyv1CzFPpqOj0MMcUKz4ZJR1CRbXPeyozrRct/6hY/p3m8sDrpwgo+BFCxVxAP0cXuqifBzpIgLNLWLHqUDpROV3rssWFt3eSn5f6ekSdEO8EaltpcjRmmcb8Ys+8Al3pU4atqulQhNMVjaL2o=,iv:Hb6s7lt8+sJhlld4Xn7v2GX+lDepjs2oTCmrg2MSR+Y=,tag:f/e8f39nNeWxZ/umsfLUmQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
