apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PODY/ji7dmQWy+BUPCfJMONY8WBBeVSaUXmmuLff/MFxcwkopvdBgbufAxF42/S/h2Szgh33J3D9C8UxtZ0ey/seyF6INu+chJ1ka9yJiWEnBFleUGPuEWi8sm6ywc39O6cnQfgf7zCHIYIx+578alDMUnEV7UHFwOhNeLAdxw0vElp3HDgCZQS5dihCU+Dx5rspkHHv7+VYwh2xMM1A3gwwYOmkqAOMH8mNI3U9dSAaLkGTJARhnP+CFG4ThabtH5/Lu7WLsTrVs1kT5CyYZSqLp4iwGfDOwKdNlb5EGPK49gf5JR4OJ6SGnh6x3HNaT+CwLe3t4iwVi9+B3S4b0IbdsjW/wBgmY/Ti9O1Iy9i4wU2m4KKRSQiWuADKyWYD,iv:Ol2Ctt8BQHAETveMYAjZ1r7lytuoDmJuD4AEvrVKEJo=,tag:ufaoqH6dVNuV0XX4KRrb3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:K28QiSpn4J1Yf21rmR4js8Qbn0iY+aTCGP+31YmeMYv9LSzrlWqVl9sxRIEOs6lvGYbBdU364XGKBh6NOCZ5dXs4/DjsxalZZYZ0o0C48qvA9Brx0jAo6TecLc04aT2jiev5SBxrPvy+3ZV/2eSSZu+Kch3GSE5R6DUCoZ47QmDlCHFFn0ANHLN/QjKRAvCu4nowIzexsUgiSkOxKvZIL6HRunha9w69WGaE4f57bxrlzIUyJJwbjnTq9HGeWf9yogUWxDudC4kBg+Aqiw==,iv:zx1sfOc4U0OZmCcihucWfzgoJblsGvhtx8t+P/7KFts=,tag:W7pfQpl0exEK/ZHxt09Q7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:X61NnIWpdVptVRH7Bx9t7ZMw+ZvggQl4A7q2E3Bia9Dlyj30LHo2n9UMX2fXayU3ri4xPUfGJbe+H3JuF8gtc3XdSdA24vHU0kX36osx8SK/QfwdA1YLZXyHrRGrmSbR1XaRyYQm48WYt67DL69EHtLoyDW+fGU7pcHbeFS+7+oM7faDUMnxNX0MT+66dL3O1yd/b+/9zYENlpvpOj33QVlNWWQeMSAAQ40Q,iv:7W2zU1wxc2KP97X7wLyir1Pupn1luLkfjRosU0f6l7s=,tag:F5PkkpXrtTBdMIIWZe7wsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSWFKSUpKS2tjbHBqN1RL
            UllTMTdWY3dpTzV0T05nbmxISXdDUzRTNkhFCkdiekNLV0t5dDR3ZHpsTjFmZzM3
            WHdocHZzalUvaEFYcnh4VmUxMEFUNzQKLS0tIFZ6OEl4TDlmTm9WOEw4OUtkVzQr
            Z0EyNFdEcVB3K041M28yOVdtbXZCK0EKG5JrMUw2h1FrBGC8Crhwx0n4gw5fIaq7
            OqVCoFIjbZPC8gaVYXKeRTrerYGyaXeVcMHT0l6eEpm2LxL1WLZpyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T08:02:08Z"
    mac: ENC[AES256_GCM,data:7ku6GbWdqL7jTo/KJIk+KXRJ9AegkpsWUj7TlUL8jOqMEnSPKJ4UYe5QIaGvveOj0BqOiOik+MUlsWzVrGSh2KGO4SOrLDNy7rLTDcDhe4fK/a1HFwPmQHYmtj3yznPl7xEIRr1WrPgxNpYe1/kGmhwKMWLSvySF94Hq+G7Imcg=,iv:hbe6DfkCUsc+EvOrcbOVZ42nQPQGf+HqMmmAVe4tbqM=,tag:jjER1mgigKOQuhiSxvbNaw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
