apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XIyRXVU3Xld0kplpnvEWe8N3i5084zJvyRMPAxdZeodc4MC3t0w/fncFtaUrfP7EnTQa+/8t79U25cczZK2C3vJ5yrFgTje7k3DFj0Hpov5xkOwTC6BMoU36V/vUVCex7Bo79oEUoRe2oS6IQDdJ0ASflmGH8g/d/aMy2LN25xSaCiZmArDU+LI+Mw/sldcqImfMhZb3WcTP68ZYu9Z3wUUKYaJBxLhFHHe55UoEqT6/FjiNm3OseXfq/nRfNFaY5k1kZZ5u34NFhzZZALWlXnIXSYLJBMKHgVnWNeOEGodkUt8KTYbuBI3FYBynX+48UMQQ/No30xqPAbMbNYjkVLbutvXOMZjFQ693SAB1V5PDc64C6UDTg1aYEoZ9hGe9,iv:jno0lZsXx7JyInCKSwLxHwN1NTLU4tHeODgweeHdlrs=,tag:X6FMPyr0XEeLsDPxVhHdcA==,type:str]
    identity.pub: ENC[AES256_GCM,data:U36xL21+Cxxw0f7I3rCqVgrg95zzikF8gk181z6sj/agMFoBULfSc81fL0qKI/9YtJQkUc8TWSXlGqcrZ7pk10QG+ZdRgbc4fQN3lyczy6UwB//1tnmp+sPenTof3TkaQ4RPux15bJPf4GYaabNYkTNT4WjNy0v2q2HpS6+bwGIj7uRJohs12D+pa+SzxEcOm/o+gk+lijAg1MAoi+4HFKxRsfCxiWQfGv5JCZHcPicr1L171twquz+jvA2d36M5JjFEnbq708l2XNzrwQ==,iv:CjixEnOs1WzjvGXvsG4F8eWzYCseVHEQJA9SVt2Ri7U=,tag:GEkGAGKrU52cjd7hEhc7lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZkIwAgUhby2WMonJ3eVJumc4BmmuBQ3Rz7jS6k5TO5wGl6uC4xSXVoLMuz8IyNpIutl/PVheUUkgipjG9sXfQcRnDwLJEveCPorc7aMCiV8c7526wFFNsog1F6mCrGi4BsHWVLZBE5bNMxFD/yuT41AC0LO/LL3+3W473cW1Brdgvuob0ClJHCrDsYfhdtprbRib4H8mV8ddtvTtlYRJcfl2trGQcFxomvyd,iv:JgtyveIgEsDOH1C+lExIkxOXD4KExKs8x2Lnub0uJ6M=,tag:8b+dqIP8Wehu16upTmMQwg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL3Q0Qmo3c2hVSkd0VGlO
            OW5Mcm1xN1dNOVNKUFVBVzNtc0RVbGw4ZHg0CkR5KzJlQmRZVG9hbjBUVFBkTEhM
            WHhCZHJrMW85OTRySnNXUUpOTFVRaGMKLS0tIHlhbTZJZ0YvUUtoTlRnQVcwNzh5
            RjVWVCtKb05USjdBT1JSTENVZi82bjgKX8QKhr67SIpGueotN84N9YSEVADNb+x1
            Rc33yC+7QpT7FZon4v9HaUfh3wMq3J278kuNKxP1tcV2V8QEYUeBVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T16:44:18Z"
    mac: ENC[AES256_GCM,data:pgg4shuoNJ0pDveeGNQJUzWl4ySbCHng+xWf5a49voXSmS+YlWbBByKl/KtE258Jd/j9D0nAJZWf96FOWh0jKSr3emAe0u2r1KYkwPUFvvZ0xJhikQ8lBhWeZr8oa4XChxP/cEW8YK/BaOxc1hrAp6LeD+cb5V4ZdphRqd1BQwI=,iv:T/DTwszl0WvopW+jtGE1dTeMwIJs6w9WJZOktNzgunc=,tag:403qcYbubtSNW3RGjkwrNA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
