apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uSIJLexL43pfJFoKAi4ZSfwHjTeTVUz16Ki/RjJfzCh/GEpWi6+93tsG03ylbK/FpmuXptd6lOVR2cf6osE4toe75JWSTHs1kl9EVJ7g80dalX42zZpSaL9ybsCHfUKV5VBYqaFoCFV4Jj7mVpuaxZN/NEy5F8bPYwpWAjJIZpOMF1Hbdg6ktgFPmanqs+lr4o2qjwZH+eOwi12jdCIN1Bd638iehLCbsHQ+YDQaiu6vtErhNF5Jt8qOu6bVzC2+EwDpMOwG6Qn5FY7J31iw20T/TS59Ke3BmFl6osGOqfqXBKYu/3R7csq6RiWUI5S9IlPf0unZmU9zIdImxWUlggnBC8ELySSVWJiynjJ4LpNUK+kg9bqEnuCfWSpUO43C,iv:dHkHxToH66yEloahhGCkzdASPuEac+I3qKTrVg+lONI=,tag:gShcy1eEY96j5lTKuNmuIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pUWgX3A4WESHUgXBbRgSctlNApARML9uuivqMFdGo6bc4EusK/48X6DKiq8QmeIRLptEcV6m4/FV8IHzKX/f0WPSbVNriBY7U9tOlIrKEVHIPnAglo61esYdab9/t8rX49kofX2K+msfOBBijEifslGqO1GzeWkYf5tsS5Kxa8xoy2f1AEYztlE/hsio2vlJ7l6PADpDZDXsztJEJrOvCITFrTT755HQFB/kOORKVAD8AP/mH5eErwn+6rx9NNPFfv9XlF8FED77s6g2OA==,iv:aHgRdAGavDsPZxmH8C7NM0cD+JiVxMm7/ju/hJRAjLU=,tag:oRjdPbZ30WqGv+GhgJ8eWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:gNEgZ6poOcGZptezAYyzASC9Hq1u3nKFj2vHKwu/MDLtZB5pMga8VgtNFra5FH2sKwsIDCuk2np75arIeMT9IDHuFguf2rXVn1x5M5GtKR8JOfBpNYmO1XRObhn5bSbFKv6I87Njv491HthCmUtrpFbx7fpO2J392wbYjDdogZhTCzBbmHD4gr65cVEY3YkWdzRC568lz8Dpg9yfZhv5ZjlcsDvnWNUXoeij,iv:zUx4CtKK1Pjeq8+PB4kNZJCKfa+A8+bBmQKgmUqExL4=,tag:gjByS9QuWT1HDlkKS0nzlg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdWlMRzFYMGZRRnp1b0NP
            bjZWRUhVcFlxb25xb3RaQldpQWVUSEZpdTJ3CkFEdFZBckxsVU9ZTzhkRFlLa3FJ
            eThBQUIwc1dLMXR2ejM5STVmZTB5bVkKLS0tIHEzOEtKRGRsUG1YMUpzNHBLUWVT
            Qmcrem5GaDh1M2orejEvRkZsQXVpVmsKchKL0Lwu6B/JCEhH4ZtR7dh0/RQwLnnT
            4fO9n8zdpnf+U4fM2tHUS9RLdvv1aL2prqXGUIgb4RxVRJVwFT5bJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T08:35:36Z"
    mac: ENC[AES256_GCM,data:iijrW3ojmv/MGMWYymLrROecZAQP5o5coOR9gWmQAZueEsDiWqQnu23HyU1vIDZYuAmMM9h6kvadnQB2CaiXiUmzLJKtj5/JSKIVbPRSSDuX7PgUJx4CllqoCeZgKOHmTL3/MPWzR+/XaEunCaUqvg9Ztm+8EgnZnc+Bze1tSvs=,iv:ecKYlj0kl1U74AvC8WKlzM4+ZAMkr3NFoO6hdmrWt50=,tag:Vex2aGSWQ05QaCp40H+1bA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
