apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BOOb4Opi6QA8tge7j4UkGvWtgQUgKNThzBzC7cYQhHeXPd0+5s0nL662X4xsiIwZ5AcWPP171YHAsXi3iT61+CY9LPPEbRi6BkCgGfEJyYKn0ajgzJHhT4DI3ruFxQwvnugXMQ6T3uRXxJzsYTJDDf0uKw1Lo9UP/EN2vnOZTkMVdlQP4c1hHHYZ+wvV7TNintTGLnIp6gdW/Ek6fHgf5r8IF7KK+gQS2Jike4/oB72BBEgH4NVeRMZAiIMrRpIqjpBNCBNPT0jW9iNqwoqV6FLH2rms7dmuwxvY1Y/TD+58WEFRxVyawwZ7Aq7RTrxlK1LF9Xx0JwkgbpCw42l1bkdb9L4Muha1q8edkHPT1/KyrXQFkkWgjztTHxebaKQF,iv:0HmsqH/EEAkeYK1E8nKDMj8bVlQ9SAoDKqNvChJU3Ug=,tag:p9E1cY8zeV7ePZVhGBQuFA==,type:str]
    identity.pub: ENC[AES256_GCM,data:U4lCrtjYotWrLYMkAKmKz0Iy+Jnl6x6u5iFdFtMde2+SMkI5RdS61vO6uw4uHOqtMNBVLRwj+51jd6fNayziM+1MHhuVX+SNAXF95nTmFWT1xSwIu3Wi3R2edQUiqrkQJTbwftK7sfyWXbLKzj9H/dLYEX7o51fo+FOaYgVoR01lK3Z4DgyQGku1zOWi1RkCzik5MDqSOKK3plD+1y1wdj91uUNzmj9cmgpwtUC9w1MR7+nKcnajGmvjEyGybRJM5fqk9nfTrAs9hdkh1Q==,iv:OBEAk+J5FINu8+h0b5PUIHaHJDvpJRmak4CEcm1ou9E=,tag:xbbybz1hvQEPBedDJBxWng==,type:str]
    known_hosts: ENC[AES256_GCM,data:CNoaukJU5CrE+qfBA7jXjdPn2Ru7676yIYq3c6WSebmxcOoM8/k6PTZlbTGM2E5VVcxsNMrufHP+ycLgsoMYGyKL7txbgkfDbe+7tf2m+XxQ+bJ1Wy4MPCvMconUC8teJZcR5YjchkG8CCH80s1Uhk5Fp+oBoYuyz09bcD3a9qU0EbG30bsBTwQc6WkWsfSbi2OjUXn8h8M3LvzB/SF6CSsUtCcVMnm+jIfH,iv:Pxf6rm60o75ni2ffCNm1phCDgvEhg8udke4DOLBpb40=,tag:+wS80WOWQj/9acbKWlJHww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWjdXYThLeERVVVVkdFZ4
            Ui9YY01WTFMxTUNLNEF1ajduSDVUS21mMW1NClN2QS8zdGNkaVd4bVk5Zmw2UGtw
            dkI3Nzg5RlYvSjJoQ05ERklOSitVQm8KLS0tIGQ3aklpakhER3FwSnVMdG5yTm9D
            YjFpWnlmemQ3VlpGSTBoaTFPZ2E1ME0Kv3NYpNyCXTqKECXdR1rG69h7ZCSqWa8J
            ORUJ9+GAQHJCV36BAaDUobwDHQrPEaBT+BIER/G8Cbp0RjE1KoK+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-28T10:32:33Z"
    mac: ENC[AES256_GCM,data:ZBj8D6gFZGazb3gPI7LOOKNA4KlkQ2+3rUR51/alvuLvuPp8qrk5eVvjR+4JdNyDrlVb+5oFMdtJJkmGMINnx5VXX+LYJFdCXgr5/yI4yoI7QMXE09C8HGAbXaCviXpaaJNFP3iCO7zFl154spmqBz8IIoM5r6kBxPpj/aF6oLE=,iv:3c0TVxhdJDlaEfRoB9BaXUiXgx+0AvSprAW2ZZSfP8I=,tag:w44bXtKW2w7RQaRstLR/dg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
