apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ynK7ifeOZiaYqP9/rBlgSALVDYJ7ruV7iRP7FyjHBv5Wc3HVUc0XKQHwUu2ndtS1m7bbPBJpTmJ1om3pJ3/X3jg7baABSdH5op1Vh8PLExo5wUPq8fENcVCnepymtR7VpRHi739oQr76II5kEVzQWVKnXknHyHrOxNjKZOWC1REIDVBamwd/JyBd6fGkILnesf0VwoOXoUfKRf4zDXsSripcoAj6BYWXSbREFki6ZYmxjuhlMM67QFO+vYo9e5Ev/SEzdZTd1a0h8NNM52YKXnu0oL5VRykObA9xzZXoqGiT/NvmdDaqkTY6ojiOFeJef06wLuV9IfcHaoMwE2JEE1AD8hpeaXH6uYco5Yh0bqKNlOg5P9lHylbSdXPu/Nf2,iv:AVGob6YGoIp15pvl4xR6H9Hc3XoWVHZ0+js+KIx2DYQ=,tag:haHf0XAJI+55K3RzD7fqNg==,type:str]
    identity.pub: ENC[AES256_GCM,data:LyicnRwzpxnmfCm8iixx0avRz4MZl3+nUTZttJZmP50Phi7tHU1BGIBwsEwhb243kfOPQmYmaidFB2EAQRzXmR28H0vGxBTFuk+/7gNHqIqREgXC8Hv03mtYvg6Vk9M3CEnzv5I/D+uvbFM2XdkR+4RSZzpZHOgOm1155f0ZZHSZuT8hwbXONNHlt4ivoDydBkX26k6xjK6bi7lcjmgKyChvAyitu9gZWN5lgBYLHIMIPB5X1SpZjmjW5DoGFIZ3LxDdtsy0SMDNi5DrJg==,iv:MhnbXZbQHPZ2v6ARr09RbrvRbyNMBJmbtl2rCo/PwXo=,tag:9+/jrzSsNZBxmOuIYMXoQA==,type:str]
    known_hosts: ENC[AES256_GCM,data:4oDeyqk1siIdWQoCT4yhkc1lseRinzHqOF/eO3Gcda+8kETZKkVxyoVSoqu8rTwkh0eunEL67LgvV6K2GlFBSASp5+9KRTwXHDFg4/6SDYKIJQB1vwMGUhESjemqv05KbDXVa8cOHegnRIwx3OiK+AdNwds+obXzAyHc5/0cHFnhIV4DIy0f/a+8d3z/ZjlOanBLMBP+KgXGVrPbELKl8CsrKV6pTu/9bCDA,iv:YOjLVQezCwQq8DPWBThGRxwnH6m7sozgvNYfohdp2ww=,tag:6Yse5h9tP1joEWn0eFy1Lw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYc2ZyNnpNc0hHZjlJYlIv
            a3JBb3BiRzRxc2dRQ2VvOEtYRUlyazJwWGpVCmVPbTJxUEFJYjZVa0UwWFRib0tQ
            dEdjY0QxSE1SUE5GaHo2L0RnUlRrVDAKLS0tIDNJdU9RYnhrV015d3RnZ3gveC91
            RDlNMGN0WStoQ3JBbWdEMVV5SUtMTUkKHwQoLmHYKJ6q/HsnCnKjrkhCDhjzXH6o
            ClelEEwxRcK2pR84u9ZuA3s7f1AAQDo3DOVAnOPpWrqEaTv/3xvZIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T09:18:39Z"
    mac: ENC[AES256_GCM,data:/Z6dPaG9KYAWxly+8UKo2nLK88bjxNOghA7Z/uqzzDjtc9uzV/Q2pyXlFTMevcFkpBWz4tPtl49W6C/MUdpj8n9CCGZ+vtIOBr3dE32CmwSc8dVGEz7rPuB5z/s+SUN8rj+LXXLOqvXBtkxA6gmFQGW7mF49RhXsCFiGB7ADOZE=,iv:eaOSY3+h4CaVRhKpAUV+yYzA+FvU1tTFi/f25GduNak=,tag:KWGFTG1h+ouVFcNBnDjFHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
