apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UqMw3VC8JSS5euwP3+huuhOm71dxjIwusHCgDLgLXINpQ75PwS+POMeHiTc6VbBAhtldB/dZPxh1T4gw9yy3BZDwljgqqIZfIOa+RyFQya48whh2C6woch6FTynLrOmdt2RueTXUy2vBn5l/QF0dbtU/DVNiUv2NxOSWW4XidowwCxUfDFA2TVQZXcMPq6BybLCDOiPatkIXNCFaBgJOcpyTvE+gpsilndICSnkubybJWmcKvcPmVlCrL9uFqTUj9SV2WqKc4KzZbF5lHVVCqED76+Xue6w157yYeZSD93QvGAYNp3KbDtJm4NBq2vgv92GLVTBxjCaTRF0ukKe5Vgz2FdroS1TGEBScEqLVpG+Dexl8PizAzJj3ddSVNzhx,iv:0IW472ykq6/EjkIi0YZQKu3AYFYZowA1s4Hfy28sCQA=,tag:tzf+i9tQcnF1t0HoJvKyiQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Bi0ZX3JJ1LETtoMQHR0rn6K5QOTpjjfERYyxyU8Eo2LFpMDwwnhGNWBRITfrxQcB+pJYPLpz0hz1029ztHF8dUSvpRiNjcEx3OAysW0pHfO6ikuoHSkEpDMt2YuVP8F+Ea9G3GnfMsBpHDfuVD6juxRtve5ruwHaD2OE+HKUHr3d2OJQm5C95ljEkA3gDBhshTxrkt0AZ60GpLtG4x6waiPjTb0mnUvMy0+isH+EaG6gBp/ht/1mTArQJpvV6M5vhMWCRTOvnocBQETawA==,iv:3Y+6h/+sA8V76El9B20UZyJjAGUC+avZydGwLvOespI=,tag:yeEHPzXtevnHJ41xGMOq4A==,type:str]
    known_hosts: ENC[AES256_GCM,data:AOyvrDcCsxNYyYKEhTl0n8O3/6ApVKrjzBtfwhBm5Ei8bdc01PNQVnkSzQ0E2/AScW58RgdPLSjAcdGC7B7sQa485DgIlWxs1j36Fe9q/HZFOI1aSUh4e6ybdi9iFtn3+dh69U0IJjrj6TL4dHQWDqldy/sl7tL0KDAYQk1t6NOIxGhph/khgRHGDYlJ26EH1gIzCGJxTyObNhyviSl/ubEnqokoJArFdmJx,iv:Z3qnbN0xVWVJODi5WEv6aLqbnymCUZOYaqp+2XBOTQs=,tag:lKEnF4Hl3oPi+adviW0IPg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveU1aU0NYNkR4S3NuU0ds
            Nyt1RHo5NW5PT21xalJIQVpOZzhmOG9iK1JFCkhJVGhmbm4yNzhDQ1lBd2FlUXVt
            T2grWVNxOU55NENKeUNCeU9oTDl4Q28KLS0tIElNWkc2Q3RPTUxPbnZRQmZIOXBP
            VlRydi85WUxaVTVwUzlRaDZKQ3RrU1UKhIRSpyIqt8/kp86BYN/BP5Le9K8950iu
            GENQOvLNhT/nRoQLRGH9raiIwi1tJbIKALHQxhecH5jDZPoc/1ot/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T10:35:56Z"
    mac: ENC[AES256_GCM,data:VIhIAhYXUur4hKqrEKI49Pfss59bBSaQ1UVMHNCnoTUdMVFvTkyyNJ0FZq2+tNSE22mb5aG5lpk6KokhGbuiOQ/dwe/aZunjJvGFa37TMD9Z/YSLKmZZzcAUHdQAJC1SgOsIp19LFhrD10wQwbsfkPUxPD1+EJ06tfdhnYMgYKc=,iv:8f7FrJ++ooN5c/dVHBIAxrJTlbBFCj/1c6/iwl2cSDw=,tag:htz7HPNjsUOClMsbHnURmA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
