apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9XBiXwQrHfriP6/XY2tC0+/yKYMP/51e+C02OHvwWLdmy+KRaSS9IbEXZPlEWSDdPNNM+xnihzD7Rf4wfmJjpWCWeS3EM80wBIVKD/YU990e/JRP1vnKJaA6zpxb/YuHT9HsTgf6oZQ0xLKACGvvgu3QaW85fuEsufAgsCwK0JnWmwuBEBJ+loval86NgdMgHgOw9mM3uBUW+//0OKTLf0L/I/1XfXnhH40aW+xXI1BpSqsqbfCY92TNaa4EcPaFDBKXyt9sH3uDbDqzbCJMq36M2uLe6n4NXmZh036bpyN4XUDybRaXSpjiRvasZcinXC0ySAak3wqiMWZ+30o0OUEeAOLHiC2qyNqoWuq0Cc6UONfHK9JBba+b8MQGTWid,iv:YQdaTgPFvNUQSAY8gnFk0seDv2gI1WApYXccLzurocI=,tag:6GYFC1Wo+P6DWbvQiDZ/Uw==,type:str]
    identity.pub: ENC[AES256_GCM,data:f2pesR3JyASfppXqotuKJ9nd81b2MhmjXQOttwRZHf+41TW/cH7GPBCFExW9uRLTY5ekn3ZxURohW4KWosCa4MPaEFXzYSNbLr5ph261iNg3N+jFZbrc3I1azV4smAm2lxbjbuFaZAO9zBYFZR9FCzpWgYMgPgQFvE7i0YKyjAfUJkk1tkTcoPZ3z7uZ0pZrDO8og0pPl+7sBag9jN2Tpt2zDktM2qqxO7WKhSoUTx0lnk37crYndo5oGLDYRYp/pFlNLYeWtZP4Wi3H2g==,iv:AxUklHscXJ9k+rGEKFEVkrVSn+CJdQtcdxk3D2seiZ4=,tag:9VmtFPVVKORnRSnVrSEZKw==,type:str]
    known_hosts: ENC[AES256_GCM,data:DYa8AU/0xlFOCgOqN6dsRDC48/eV+IvhPw0FGB164E9YuRQe0rHlfRemNMzu1egc2gE4JEK6spGkzxa9VfyjyXiwAj4n/Y+qiFrXoyICTcA3kegzarfUqd5rK+APyQ9g91WVOoxPxl8W+aj0VnDv8DhFCJ0uNqxmgHJv936jTpEyC4QtlZ1Q8bNSUqBFogOvs6/h9G/VOL/VbfugDdxUM6CUkQNWAtDmz/9l,iv:G/0Fo2HbbCa1Wi2BQd/2tEw+8iB2Z3H8XGaLjT/RbeY=,tag:jpmKri0Jt0rhG4msV3nXkQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY2ZuSTRQOUNZdDhjRzY0
            TVVaRUtPS0g1ZFNrSzUyQVhHNTRuejhNL2hVCkF6YjgzL3BjK05OM2o1ODdPVVpR
            TTU4ZDlob2src2w3STZFenpKdHNGUG8KLS0tIHJVem1RZ09GeTluR0pJdXlzQUpM
            Z0Z4QkNWaW5qRkQzbG5zRTBKMTJrZXcKzIVGCMXVYsiYF3I6/7b8O35sr+NrVCnd
            NJJVr2z7/q16vPfBf7vE60YVgFemKTemkKy2xSyfItTjmiKt5gszZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T10:53:43Z"
    mac: ENC[AES256_GCM,data:yfNeF7hP8VFj0ALFr8z3V9+F98y7NydtV89gkvuU51t8dMe84RIwZb41f0ES3kqmrDaDWuCgy7saqFJEH8wImcrNzqYWu7d4Bny0ioIrhMSmqWUeTkrwuYccEW8jHErJA8gwDzBjsk/vh8arTh7DKmNRRaQ4XDcZIed3QiKamAI=,iv:6J7S0Tt0CHuIt7W23DDW0fE4o1nubhqGJe40vL8DkOs=,tag:Y3McPSM850XD0Va8GGax+w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
