apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:y5YiimzcjicdNO1yhSPKgh5fEUyO7fsZLtQF5bhmPJgRHeuUkhnq2bQ+cZQVP0hh0Ivsj4TzrcpFBv68j+z8RBU3mZ1yMWyHZ9tlPiBa7tWSITUKbZ+OMFbx6a6b6IWjrdrPx7YJWhvj94QbChOUhIbQJ6E3cWL+Gw5/P07imuI6C8pUxR3SKokik7Jnmb8RqWcmhtcWKdRloGdjBnhiTTiGFQmjwYwi2l8Rwqkzir0khYHD2SQKsoPCOIUT0Ak7dpsTE+fyiMxQvTuuL2KKmBQRtxSyo+BSvpGKU/I5PFZh2DWOwtAp/PBb9AsKVR3APzwrfCMf2j0RYa3ANRIiCfBi2ffGX3zQ3W7d/Yh4RePUWesR2qEFT7ZCHMtBY4NG,iv:eZFCR7/oGa2Ewb8duE0LIO8XFjoUbZBuGcIfTIHf5No=,tag:emk5rBcq6BMFfKiCSc20vA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vbX4Xf3Pzph3Ss0GQpvqnmrqAR76TUCLDQ/TBFhIiUtgxBsMnJoy4OWMklyrw9NLJEKg0jOyev4BnxXgdaUUfEKW+cBkpeYpVf6Tfk7nUs3yYraV+GyuFlM4BQPZtg4Eud5dhIWb4ouC34rqgIvubAWNzKrhYXApfb/9SSIaCtvJgqafccXRzo2qMNL9PT0NPvTuYnNs8epWACxv/cH2Ajtej0nuBL5T1j5UjWFtluRr8JJEZ9LnvdvcazP0qR+zZPxbR+bJDtap6XLShw==,iv:TAIfUmf31+RSQMnKZIScEMVq2nYpljh/LrOXP4ng2fw=,tag:L9dpD1UuhgugI3vsFy2R9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:n4vilnsqFfmWNgPZXGce51HoRDWLQ9TcvwHufB3QNy+hDdaiQRQuRiu7uyOc10baGzTd0hpmrCiOekMRikSNlhrD4nGdtyTWob7ylxCC3s/Q5hZeQSrTnqf+XzjT7fba7d/2U0fK2DlDzlDdj6cMLlm2IjOoGtLW1dfa6aJSynG6SxZisaguDC4ciQYeMV3/XnHHMkee4c6HpQWgnLNn2Z8D6Qo2ElYLAXOk,iv:MU5FDjeIXfPvMQ2c3TLNxHwVp1xxh6yU/wO2IVqIu3U=,tag:j1RdeBBkUo6V0iL+A/XYNQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdDk5YlV3dWtSQ0NXV2pu
            a1BFS0FvYzgvNUp1Sjk3VjFBQTZkY3VsaWlrCjZvS08yb05ocDB2RWZncjR2bTBo
            WVovNUZwd1RKUlpLY2FXNk4wK01MZFUKLS0tIEt0V3pHZXNBTDhIbWVSUXBBdHlX
            SElTeFlwbG42VGRjMHAwQ1RGbkxRcEUKtgF9HeOBrhrvOHcQwruemvjpLTqLWc8R
            evatT9pwZH1F7BbOCr04Qgvc+pT+MOS4h83dZUUztNaNVuUBvmo6Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T11:33:51Z"
    mac: ENC[AES256_GCM,data:eWKlsM6rf4IStcEhT0wLETJSHyLz96omG82nJsvt9sp0Hr4txUHR2nxTjwGjmo/f3UCj+mWckLDbOQNk5h8HRUnKmu96KP6h1jaNsKoZ8VB8zIhyRHq89S60PiK1nxLo6G4EAiDMW5zi93LO085x79hDO7+ywXF21S1RzJIUK3Y=,iv:7dTeiFfSJooG/rvPAojFQ3tQvDFJSdUlEVFcMSdK1+g=,tag:6P0Tb/qZBgokeJa61FvPbw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
