apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Fu1Q+aqnz5aFPvBxnTbctkeKntG0HqTlSYnyepIkM3XinjzEGpkNRcdG2Rl2GgQ15r3mDS5GMVPvpVjgPnCN6FulLMVQt1Re14DIGmlJJtDp4fVB9EvjnaPk7Lpz34IrGv4h6CwKLWaY6EH7MrLXHztww+iihSE6m6h0YLn88K1MNjLbvjNAU9IkGqi7hifUkS4QnllNS0Mj/przdoTXYFEBT5dX+v15909kVcFqHahqGW5bdZtf7WWRnXt2X3q1S40Vj2BiVn0CuaMioNb+Baq2oDO9teOMSnxx7DaR+Dlzp0vStVXS7AIM6BoKv6givWsuneQsi84vT8naO1CDAhZWIim9OvP1vkAPGtMkc0IAm94Z4JJqRRypAoFA500b,iv:cmcySWlEw8M6TKmiLFm3PtQzhu5WUaizzLPXBdcMQkw=,tag:Sw8Su2hHijfBS0TCDaW9eA==,type:str]
    identity.pub: ENC[AES256_GCM,data:VF1EbBCsPrKgR6Fui1iJcME4H3cQnmlxAKrtBTYNbs/cO/GQqvpIHHf9HBwsaX4qDId7CwFOC0xboi7KZAHotOSO0xUgrVYgPp7y80VETm16JWVnXPs/Sj2YqCOHl4TaM73tq7Ruj0BnkulMv/9075WZWk3WLpHFlK2kEd3D2Zw+tc+iXE2Q9FeByjrnY6K9Lroje9w8W472wgOad41ox52j1zGEYikTsKSKXyNmzk8wfV3HhthsMWY2CydY0hpeVjn/PCmU5jiisaNCMQ==,iv:hrHiPe/HYTVcUmC6U/O4kI0gN3UhxJ+MmDr2D+4rFqo=,tag:+zD1P0R3PzEJ9CqIuc1B5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:I/hR4wGNSh78AoFyu6pU48htlFSqFjct0WSS8a/EbZDqUCAwd5M5ESxOgbY3gnYv/4yds0rp6sHTYb5QTzfEkjrfkJ6Wqc2qqqNdSWczi95Ha1C3hrNX+YyvdhYi7JSTy6pNAoEPBR71gESfo4tT8jGdDUMV6McSu/S+pi6Z3uM3PpK3jMS1AslIaCc/USIyCz8JhAQV8L6d6+0HIDhN7d8f6jEyTZkczu24,iv:FLcp92BU0QbOmHPoCwT04Rb4Zfb/jL0Hu1qOy/ArA1c=,tag:grXjFZ0fnbo2LpzssUEp1w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDYxNEJPOUpJVFAxRmw0
            QkFRUVkzVmhMWnhVdllXVmtyNGMvbUtTS0NFClhaOFBJYzZwUGw1WlF1R3p0UmNF
            T2NQcTAwUThaNDhJaWxmckNiWXpGbVUKLS0tIG5WY3RSZXgzVDZtdUgxMHN0ckFq
            aXlLNjZ2UDdySTZMZG1kcm1vNFdDZXMKGuQTMuoYO3LittJTk7apfe/1zjoJPgMP
            K0UmeXC0TSaiBILNABWrvf58QMHVLGJbwKL6EUevQJoVQaPP4bKuSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-09T17:02:38Z"
    mac: ENC[AES256_GCM,data:E91zzAx4/pyD60gPPiVbXA8dHC/E8d1mNm1ArpWCY4lYpfK3x2xuYmevhEyZUW7LEzH1w5FrztrpmZU4uZybhbqExLbiOROqayyjDKTjSWRpSP0LFFg1ww9o8yXgESyIXpBDsqXRf2yVcNnWV/POZ/+NyEpTCIckI7us7E8ysEw=,iv:CPvQEi6VDl4dJDuUzviBENL0zRkzt7/2FEg7vbLL0pk=,tag:j9VGA1XQMXfu+Ly0L2PvhQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
