apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lAFmNHlVj+hikLkIxIHo+vQSHpnUqa8Ay79F1JPW4WeD1cQMYgcEGWInwPfJyVCiddvkWjyCYwmVcfOIVC7IPE83ZLf6UDP9fGgJ+55DBvQHDNuLVlLBefG17Jeqp/MDldXOwmEIpOgEISW36BToG4yS2juBbsNwJbghBvpuewASQpszB/Jj7x8KMWCBrKJ7yL7lle/rGOOB+jBd/iMOrmpzZvkH9we2tBcl0h/fDY2nK3QFKzVICxXs2bOzi6WRMGSITX2u/KeLlMgqRXHKzNv8+V6Elb5CpfvjjSg77Y0jiKwRGpC9H4gEjtzRIwESaIWf7OApObSWCVlReX0oUNXx6PBCSYSkZ5k0mndPlKVGOWCWZ8/R9Gc1fXfOGxMW,iv:h91ovmLCxgUTMsIbAOyJzLZV2zxBHsAZlqzqqJas9Q4=,tag:4ibiAEZDjmMdD6TlPWickg==,type:str]
    identity.pub: ENC[AES256_GCM,data:raKUNsCmHdXgDmfXHx31WXYaVVELVDZBLTnGYjQBjCIR5O8XZ8rJqqaxxu8K5fl2hxKW6DU7vmGu3m18MSwhhZy5vAi9OZcPBd0geB0swyhwn2aeWNHGegR99reFEwBjv7L6GSbRexPvNHERFjWzd9VCRO4TUsMKkgphGgzQ8xICjakVfmFHLIeZy3GxmmCCPR8Q2hHl9+kWcVNgBO72mbbdqTm+3C2qVMqme0BMvjclMo/ukTp+dxvLtMN17vTOeneXFtNOoeVjcDYGFg==,iv:RBfq4r4i5QRMAF/tGLKQf8WC4SHXpdHqKYSe5hmG10w=,tag:9bjRWk+zqh7Ql+FQ6XW1yA==,type:str]
    known_hosts: ENC[AES256_GCM,data:fxNy/rxfFT3ap2VuOhF7Ooy/3HY0HDsa9zcQtFHT5N7cM6r2CV3vpd9WTZQ6/5LBbV+h3jMRKp8pzQCbZz/u0019FPzqOz27KLLMG8EvrCeJsaSUHVD68AxF7Ux2MPZt2oCQsiG6oiUwJ0jPSzQf/ItTdzRty1lli3L6BMlP/588wi9GK0K9Es+FDlc3DBpFUO3jMraxN3PR3GN+uSjwhU7pwxSeRnBg4x6o,iv:s1XxDHnqx3fwIXIfYgM1zbT8kKN6o1cPcf1G8XL2lO0=,tag:0nluXxyDXbi/LDbvK2lFXw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOGx1bzY5dlZ1UkFabVZ1
            Y1llbXdRaUNtVnNOSzNtVGdNM1FHWTdSMG5VCm9rQTc5ZnpKSkUrckZPUlZEanhV
            UTlJWVBTZ2tveUVOTENsYnRlVy9wMFEKLS0tIFFkeHBSeEQvR2grVGFwc0t2cVg5
            K2syeS96TndQM1JBVnUyN0hNcXQvblUKLHXyIyjeDHr0V6zBtkSYPk2BxD5Zu3+T
            kuRDaU8xxb1h8P8o/H3r6YRkAfiv6ZzA8fUoYnUyxJLV+aivv9LuxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T10:04:39Z"
    mac: ENC[AES256_GCM,data:XFj5E24QOLdrWAFQs22qFCLd1gUTFIADcZNcXsrzlP+tZ620Ng1rhm74GVSJuA5UhvSNUCNFEhGWjG30SnYI6NTzZ5BwJACegM9x3wYlYiucz4HJ7ZLBPKaEdkbugB46MnPrc2F8Z3QBydDYGpNsIjPmXGgjlqyrxmaeTEeoVJc=,iv:JW4Mq63qzsT+0k+QTMkSm2yB1bRqNEtw15PzKTrucRo=,tag:QhV0wysqrIDEyD9KA+fJnQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
