apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:W3ey149n1QpQ9PDFc2IFIsD+cFY6cuNc2uYjJmOl2pfRzOOVNrsk/rb79Od1WlTHRGfM8lKe73NN/s/bGOrjxhXGal4pMzG8QBodm72EhX4E4KQpnf7MsdD48HOQG3JV2x86IdujjB73Uk2VYM88e/SGWkZah0shMMkLqLmT5sOu4bwCURVFCPLlaoavS5wSvdW1eqnzeGfSO74l9qBjzOnP8YZfAu040a77iZ/jqY6NBWJGDL6V9JUQu77yl7hZOtGRpysgcRr+VbgcXiVpWL9Zy+qCsaQ7RrkfgcCNBz1Bu3gVKs1YDQkd9rppk5HNIodPo8ZHT05po8wDkQ8GEYM5tuIEzCUR3OZEthJqenDjkFlHfN9LgVNfTC84ZLiu,iv:DLtu0xLYNvBMiDMMNDXbEpR1taa7ETHuJMmyeJ++wO4=,tag:JApfo62al/9qUPcd0YRm3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:LkyN5nScfz0Awb9T0CAOaVxIL/meOgzpJ/P14IYgX7QSx55xmRy8op6xJuhePSaO0pDaR5Jb+uAfsWNTcqJbSUYG7VMhfzkahyuTU3VuHTTvBGT1bDJosFWxq8sbeldjnenRmfmqVXa/Rd5CwlEjC2ErfwVV5mXvlj3Jn7SRlT23vlvazUl2lbtK+M0AdZW5ZujB6pEZz3F2ISSyriopuYGASJCJUgURFpdO4WPT1xrgIXidgk+b2rjROKPNihY7bm00Vd+XFRnX4qwGKw==,iv:d84U4YKESO4W/GBlJ70daBQ+GjRHBYNfsvDx/5raZUw=,tag:sCXr3SEru26O74C9fteTjg==,type:str]
    known_hosts: ENC[AES256_GCM,data:UWnmUBt+8VWxw3W1nUaPXD9exM6lFbbz/MOyViaZfhHm4ndR3DC3KziIiPzsAblO5Dc2SB8eGTK7wlJzW2mjURloeFTk3j+sIhZOxKyiM6vCZvDpGM1RPLr5qR0BIGEe1bCUEaaUEs3jfGXLN72zGZAhQCxkXjPkn9bcKLW8mPJdHVBUeMEpsmYtHk/QwlR5X92Bl5SSpBkrr2k3s7HckBpm+cJeWPYHVXXm,iv:tey66qOwZEXHhrEZXq07jgV7lUKAeLxJlRcWY+NjFWI=,tag:LmAOSf1AIMOD0yl3zhZe6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejBnQkR0Wmd1QXFQMUZU
            Q3MxN20wR3hPa3YyaVNSeFhUL0c2WHN2K1RZCnpLZTI0R3VYZm5yNFM4YlRnSlJP
            QjdVSWNhUXJTY3NCelIvd00xN0JJVTgKLS0tIEp6WTRyYlFpUG4va2ozeEZuS3lS
            cDFHbzJoUW84U29lbUtNSVNFMFl2MXcKDirwlTq/ttBd+4PJbhNq8yYhcAEmy7yb
            YslNTit9CYsh0mUrAFNZKUBUYIW/68AV3CxW6g0ij23QUcc5+Idm6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T14:16:56Z"
    mac: ENC[AES256_GCM,data:YKKCo8V9TwixdN9+5z9G6Nmt/NeCy+akKKDI4mZ0omZnwE5uAOisH34p56hwBCLb0WyCT2Pdc3Bc4USCU10ntxUtLe/OAxSEd/12O5d5SAEP6EgMhcDB29I3NwKleCu627QpgSIcl199+JrccUO2nJELPFHInhOAG/3jqcUzAQY=,iv:B7JWx0AGN/K39el/QiG1/kebATiKcIPXiIbXAtd83kU=,tag:Rhxs/ZDUpwASO5YktVYQSw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
