apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NN65eHygEkN3aNBfnt6ozBbR4XSQCuXHzXnVbHHpbFexad8mQrhSiFCJojesZ8d+QG2d/i065XJ4pMiIaZLNLS17B5+4LlTWUl5AkfjJ49rO2zlm/GqOcTaFUmfPl7bQjkdGm71L53c3TatbAI5VViCxBBAYtJoSKmnOZRoiv7vMh3UvNRaXTokTqzSFpg4939UMsb9TW6DMhw/iiN2z5HjJT+5Bj18SAaj5tJtojW1okIiugwJZPqD2Jt9xe4Db+WqQmZM/vWIWnNEUJ1VhkZIObMfNd5DVZTzofsfDk5EDQdDk/V+uBD35SCPUyo5eqBdX5k8d9CPEkzk/msi/LB94LqBeIV0cxAmrc+MQpui8vmlHBhDrHtz8rtEWt3l8,iv:wXb+U/cVATWLKLb/hZ+AAA4eo8fgjN7RlqcxBQ6zjYI=,tag:jQypy3rlz0tKuFSXeUSOMw==,type:str]
    identity.pub: ENC[AES256_GCM,data:HTrTswfNGvYg87mFmGEhxdNhvdHVqqMHvBClXG9+NGFhoPxGsoejhYQx+9hu9ox4jOQzQiVVtgjTqdM4M34RKwmbYoQL9abK6F2vuyMS1T2sFGAmfeNKAc5fTnTbDe0KTUU3PJr45AeaZbhByfdLwm9rjs0843pWO/UL/j06LOKplalh8fq5/2tLZDM6YTHESwRPknc+AxLCBPRFDuC77mOXxPdHc0aQcsAYXaOad7duEZQImTpoIHShjevaACVy2bAHehF6yXMNNwl0TA==,iv:lQ6xCjH81ekTGOCgebMhbUee37MBBnJu+vok7RDudRw=,tag:16566kkkBKSxKZ6xakA5yA==,type:str]
    known_hosts: ENC[AES256_GCM,data:SdTZIERqq8OEkcHvRuQ0U3M4EECRqTiPImLhvhISou6oVUPxUfnkJdMncgMm8zxS2s7dAh6mBnHTNcoAPGaPRmYswdeBzUT2N9J3h8YAnNjGxjL3dGm8Dd9XAD4yjs2GKJ1tPGYgM/qePdWGdH7zyIfdGfLJZLL0bT3WJ2Q3Mmmajs01FFWZfb2WlTe0Wq2YHQrzCFPydQCCbQysDFm90WQDy/ZheoE5ORg7,iv:Xx5uSdgwvwFq+VP8MsAZecu9RcUaHGKLfq8FggaMznk=,tag:1wIxquk6OcN2jfosmOhIGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xd0fy47qvxpnrtdllmcxhgr5famhuumxuvqc29v53elh0xvqa9nqlg4htq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ2JyUndvVm40YnlmYXVI
            S2p1cm1ucnFIT3FTUk9zSzRiejdacE1CcXdZCmxTVWxKdTlCeHJOYUNjY24vV0Jm
            NlJmSE10NWdnTXBES21ybGdEK0lOZjgKLS0tIEhJMVVUNVFDTW9FVlJ4Qk5LcG94
            azRZZUVaUkdGRTQyZ3E0NEFxSlp1YzAKxCIZdrU3JXMg3wIm03Ps2lkSifdbS2Uu
            A4U0tehlisk0OCcLCeZjxAUg2SwZmBEqREAQATHjm6CoIGqeuzy8cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T10:52:14Z"
    mac: ENC[AES256_GCM,data:XMKvQEjz22izBcjFGvdYwQYE/jDdlNw2WM86oX7SRFz7e5dw/JGWu4li/55ZOKXkyml40NF1El4kRf3bFF8s8eh0YbOgKlvnsioRoDNSv4+ptjR7vzhjjjn3JDwIpuQJzp08M6sc9kR2LNP88M+bvFOhxYIH7bPLUF9SsK8VGec=,iv:BvjAWaszsWn1XGAEoPCPN2d3m+lPHTXLZp+0jmeRhz0=,tag:oG5n87blSrOJ9Sv+4a5a1g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
