---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: navidrome
spec:
  interval: 15m
  chart:
    spec:
      chart: navidrome
      version: 21.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
      music:
        readOnly: true
        type: nfs 
        path: /mnt/AI_Storage/Music
        server: "10.0.50.10"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: navidrome.cloud.dev.local
            paths:
              - path: /
        tls:
          - hosts:
              - navidrome.cloud.dev.local
   