---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matomo
  namespace: matomo

spec:
  interval: 15m
  chart:
    spec:
      chart: matomo
      version: 15.16.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    mariadb: 
      credentials:
        s3:
          type: s3
          url: "${S3_ENDPOINT}"
          bucket: "${S3_BUCKET}"
          accessKey: "${S3_ID}"
          secretKey: "${S3_KEY}"
          encrKey: "${S3_KEY}"
      persistence:
        data: 
          volsync:
            - name: mariadb-data
              type: restic
              credentials: s3
              dest:
                enabled: true
              src:
                enabled: true
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
    ingress:
      matomo:
        enabled: true
        primary: true
        hosts:
          - host: matomo.cloud.dev.local
            paths:
              - path: /
        tls:
          - hosts:
              - matomo.cloud.dev.local
        integrations:
          traefik:
            enabled: true
