---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 27.6.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3_ENDPOINT}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ID}"
        secretKey: "${S3_KEY}"
        encrKey: "${S3_KEY}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
             enabled: true
            src:
              enabled: true
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: internal
        hosts:
          - host: home-assistant.cloud.dev.local
            paths:
              - path: /
        tls:
          - hosts:
              - home-assistant.cloud.dev.local