apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - helm-release-oreste.yaml
  - helm-release-tizi.yaml
  - helm-release-casaebottega.yaml